---
host_ip: 192.168.1.1
nginx_ip: 192.168.1.2
network_cidr: '29'

tinkerbell_network:
  version: 2
  renderer: networkd
  interface: '{{ ansible_default_ipv4.interface }}'
  ips:
    - '{{ host_ip }}/{{ network_cidr }}'
    - '{{ nginx_ip }}/{{ network_cidr }}'

# check edit-local-secrets.sh
server_username: ''
server_password: ''
registry_username: ''
registry_password: ''
postgres_username: ''
postgres_password: ''
postgres_db: 'tinkerbell'
facility_code: 'onprem'
osie_tar: 'latest.tar.gz'

tink_repo: 'https://github.com/tinkerbell/tink.git'
osie_url: 'https://tinkerbell-oss.s3.amazonaws.com/osie-uploads/latest.tar.gz'

project_dir: '/var/tinkerbell'
tink_dir: '{{ project_dir }}/tink'
downloads_dir: '{{ project_dir }}/downloads'
deploy_dir: '{{ project_dir }}/deploy'
state_dir: '{{ project_dir }}/state'
certs_dir: '{{ state_dir }}/certs'
certs_d_dir: '/etc/docker/certs.d/{{ host_ip }}'
registry_dir: '{{ state_dir }}/registry'
workflow_dir: '{{ state_dir }}/webroot/workflow'
osie_base_dir: '{{ state_dir }}/webroot/misc/osie'
osie_current_dir: '{{ osie_base_dir }}/current'

create_directories:
  - { path: '{{ tink_dir }}' }
  - { path: '{{ downloads_dir }}' }
  - { path: '{{ osie_base_dir }}' }
  - { path: '{{ certs_dir }}' }
  - { path: '{{ certs_d_dir }}' }
  - { path: '{{ registry_dir }}' }
  - { path: '{{ workflow_dir }}' }
  - { path: '{{ deploy_dir }}' }

move_files:
  - { src: '{{ tink_dir }}/deploy/registry', dest: '{{ deploy_dir }}' }
  - { src: '{{ tink_dir }}/deploy/tls', dest: '{{ deploy_dir }}' }
  - { src: '{{ tink_dir }}/deploy/db', dest: '{{ state_dir }}' }
